### ISSUE TITLE
Accessible alt text suggestion

### ISSUE THREAD

**Issue by elenalape** [zaneshaw/svelte-holopin#1]
Hello! The board's markdown snippet was recently updated on the website to include a more descriptive alt, like so:

```
[![An image of @username's Holopin badges, which is a link to view their full Holopin profile](https://holopin.me/username)](https://holopin.io/@username)
```

May be worth syncing your `<Holopin>` component with what's above!

P.S. Love this, great idea.

**Comment by zaneshaw** [comment]
Awesome, thanks for the heads up! I'll get this published to npm. 😄
